from __future__ import annotations
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, model_validator, Field

class ArticleData(BaseModel):
    """
    Represents raw extracted text data and metadata from an article.
    """
    url: str
    title: str
    author: str = "Unknown"
    publication_date: str = "Unknown"
    content: str
    word_count: int = 0
    access_restricted: bool = False

    @model_validator(mode="after")
    def set_word_count(self) -> ArticleData:
        self.word_count = len(self.content.split())
        return self

class ClaimAnalysis(BaseModel):
    """
    Holds structural analysis of key assertions, tone, and framing of an article.
    """
    main_topic: str
    key_claims: List[str]
    author_stance: str
    tone: str
    framing_summary: str

class Blindspot(BaseModel):
    """
    Identifies a missing perspective or factual gaps within the original article, 
    with query guidance to verify it.
    """
    category: str
    description: str
    importance: str
    suggested_search_query: str

class SearchResult(BaseModel):
    """
    Represents a specific search result found through search tools.
    """
    query: str
    title: str
    url: str
    snippet: str
    source: str = "DuckDuckGo"

class Evidence(BaseModel):
    """
    Pairs a search result with evaluations on how it relates to original claims.
    """
    search_result: SearchResult
    relevance: str
    quality: str
    key_insight: str
    relevance_score: int = 0

class AgentState(BaseModel):
    """
    The tracking state for the core orchestrator.
    """
    article: ArticleData
    claims: Optional[ClaimAnalysis] = None
    blindspots: List[Blindspot] = Field(default_factory=list)
    evidence: List[Evidence] = Field(default_factory=list)
    search_attempts: int = 0
    confidence_score: int = 0
    search_queries_used: List[str] = Field(default_factory=list)
    status: str = "initialized"
    
    # Tracking fields declared directly (avoiding extra="allow")
    search_results: List[SearchResult] = Field(default_factory=list)
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    research_duration_seconds: int = 0
    metrics: dict = Field(default_factory=dict)
    source_diversity: dict = Field(default_factory=dict)
    stagnation_count: int = 0
    last_confidence_delta: int = 0
    completion_reason: str = ""
    confidence_details: dict = Field(default_factory=dict)
    phase_timestamps: dict = Field(default_factory=dict)
    query_history: dict = Field(default_factory=dict)
    blindspot_coverage: dict = Field(default_factory=dict)
    planner_decisions: List[Any] = Field(default_factory=list)
    confidence_history: List[int] = Field(default_factory=list)
    unique_domains: List[str] = Field(default_factory=list)
    llm_failures: int = 0

class PlannerDecision(BaseModel):
    """
    Decisions generated by the planner to direct orchestrator action.
    """
    action: str
    queries: List[str] = Field(default_factory=list)
    reasoning: str

class BlindspotReport(BaseModel):
    """
    Final synthesized report on the blindspots discovered and evaluated.
    """
    article_title: str
    article_url: str
    analysis_timestamp: str
    main_topic: str
    key_claims: List[str] = Field(default_factory=list)
    blindspots: List[Blindspot] = Field(default_factory=list)
    evidence_count: int
    blindspot_score: int
    score_reasoning: str
    missing_categories: List[str] = Field(default_factory=list)
    balanced_conclusion: str
    search_attempts: int
    
    # Enhanced tracking fields
    confidence_score: int = 0
    confidence_label: str = ""
    evidence_strength: str = "Weak"
    completion_reason: str = ""
    research_duration: int = 0
    source_diversity: dict = Field(default_factory=dict)
    report_version: str = "1.0"
    
    # Analytics fields
    search_metrics: dict = Field(default_factory=dict)
    evidence_balance: dict = Field(default_factory=dict)
    quality_distribution: dict = Field(default_factory=dict)
    
    # Traceability and phase info
    query_history: dict = Field(default_factory=dict)
    phase_timestamps: dict = Field(default_factory=dict)
    blindspot_coverage: dict = Field(default_factory=dict)

if __name__ == "__main__":
    print("Testing data models instantiation...")
    
    # 1. ArticleData
    article = ArticleData(
        url="https://example.com/ai-trends",
        title="AI Trends of 2026",
        author="Jane Doe",
        publication_date="2026-06-01",
        content="Artificial intelligence continues to evolve rapidly in 2026."
    )
    print("ArticleData:", article)
    assert article.word_count == 8, f"Expected word count 8, got {article.word_count}"

    # 2. ClaimAnalysis
    claims = ClaimAnalysis(
        main_topic="AI Progress",
        key_claims=["AI is evolving rapidly", "2026 is a big year for tech"],
        author_stance="Optimistic",
        tone="Informative",
        framing_summary="Focuses on growth and potential"
    )
    print("ClaimAnalysis:", claims)

    # 3. Blindspot
    blindspot = Blindspot(
        category="Economic Impact",
        description="Lacks coverage of economic costs and job displacement.",
        importance="High",
        suggested_search_query="AI economic displacement and job market effects 2026"
    )
    print("Blindspot:", blindspot)

    # 4. SearchResult
    search_res = SearchResult(
        query="AI economic displacement and job market effects 2026",
        title="Job Shift: How AI Impacts Work in 2026",
        url="https://example.com/job-shift",
        snippet="Studies show significant shifting of job roles due to automation."
    )
    print("SearchResult:", search_res)

    # 5. Evidence
    evidence_item = Evidence(
        search_result=search_res,
        relevance="Adds Context",
        quality="High",
        key_insight="While tech grows, job functions are undergoing significant shifts."
    )
    print("Evidence:", evidence_item)

    # 6. AgentState
    state = AgentState(
        article=article,
        claims=claims,
        blindspots=[blindspot],
        evidence=[evidence_item],
        search_attempts=1,
        confidence_score=75,
        search_queries_used=["AI economic displacement and job market effects 2026"],
        status="evaluating_evidence"
    )
    print("AgentState:", state)

    # 7. PlannerDecision
    decision = PlannerDecision(
        action="SEARCH_MORE",
        queries=["AI infrastructure costs 2026"],
        reasoning="Need further economic context regarding hardware/energy costs."
    )
    print("PlannerDecision:", decision)

    # 8. BlindspotReport
    report = BlindspotReport(
        article_title="AI Trends of 2026",
        article_url="https://example.com/ai-trends",
        analysis_timestamp="2026-06-13T11:30:00Z",
        main_topic="AI Progress",
        key_claims=["AI is evolving rapidly"],
        blindspots=[blindspot],
        evidence_count=1,
        blindspot_score=45,
        score_reasoning="The article has a notable blindspot regarding economic costs and job displacement.",
        missing_categories=["Economic Impact"],
        balanced_conclusion="The article presents a solid overview of technology progress but overlooks socioeconomic costs.",
        search_attempts=1
    )
    print("BlindspotReport:", report)
    print("All models instantiated successfully!")
